services:
  backend:
    image: 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_2:backend_latest
    ports:
      - "8800:8800"
    environment:
      DB_HOST: test.cja8cicf5jor.us-east-1.rds.amazonaws.com
      DB_PORT: 3306
      DB_PASSWORD: likhitha
      DB_DATABASE: test
      DB_USER: admin
    restart: always
    networks:
      - net1

  frontend:
    image: 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_2:frontend_latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart : always
    networks:
      - net1

networks:
  net1: