
services:
  backend:
    container_name: backend
    build : ./backend
    image : cs686_midterm_source/backend
    ports :
      - "8800:8800"
    environment:
      DB_HOST: test.cja8cicf5jor.us-east-1.rds.amazonaws.com
      DB_PORT: 3306
      DB_PASSWORD: likhitha
      DB_DATABASE: test
      DB_USER: admin
    restart: always

  frontend:
    container_name: frontend
    build:
      context : ./frontend
    image: cs686_midterm_source/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart : always
    environment:
      BACKEND_IP : backend
